language: node_js

os:
  - linux
  - osx

node_js:
  - 14
  - 12
  - 10

# env:
# - TRAVIS_CI=1

dist: xenial
#
# deprecated key sudo (The key `sudo` has no effect anymore.)
#
# sudo: false
cache:
  yarn: true
#  - node_modules

before_install: |
  VER=$(echo $(x=$(node -v); echo ${x:1:2}))
  export FIRE_CODECOV=$([ $TRAVIS_OS_NAME = "linux" -a $VER = "14" ] && echo "1" || echo "")
  # - npm i -g yarn
  # - openssl aes-256-cbc -K $encrypted_3058eddffb79_key -iv $encrypted_3058eddffb79_iv -in travis.ppk.enc -out travis.ppk -d

install:
  - yarn install

before_script: |
  yarn dist
  bash scripts/travis-ci.sh before_script

script:
  - yarn bench && yarn test

after_script: |
  bash scripts/travis-ci.sh after_script

after_success: |
  bash scripts/travis-ci.sh after_success

before_deploy:
  - bash scripts/ci-script.sh

deploy:
  provider: releases
  cleanup: true
  token:
   secure: q2e9Ng9HL/jJGGKrIFnMkp2YmjPERIpFxJ8bK3aV1GuFc97ZjBey/WHIRZ/ru3AhpEu6Hpcf/0bviLZpwHwc3urx0PpvYZugnwYngsXhWhaALh8Z/gHOyfTA+1lg/WbaR8bDIPG6nSbI2HSPTEvwiJ7Qlkb0GDC7Hibtib0pgE2Vp0AgcRcVQgkpllTZZz6XNnCaeCagafVKicBCMJ9nVlRgUjzZREh33S5HYTi4OD11GEbzIJoDPRfd3MFLEGhuTwqu4AeCuSQohVluj/I+dCY8s2SzhPQZrojDTmGTUGM0Vq15UVLsNIoBfQWgn25T7HkC45WTnm4jQWCSdPLU4o6RAXLv9TQgSaBaBdu46G1tYVkHdqybMWlXn/jNEFGdrznHvh5lniZ4Q6J5VkUF4HJ/CShL8azGcdIv+5wirkbtrDRtPXBtb1og/xN9SVSd1rdgXVRXgKSUAsGRtNuHWpz//yVMvN8YCzA6hBdLKN927aCy1ZlXrJUMgcLLJRGBQoliWV/flSebrLu2T7/cP+oBJS2zAVohh7URUYTwVRuWQWjJihQvJzT0Yh2uea9A/gQZ/Z1eUISsrAkDPR013GlQ2oMEGTN+ajX+ZeTqIdUKULUiZRA+6JwmVk9I3VTPIfz/uYuKrq4B+Beqjft7r4Tkq4CVQZpQhS/91LX82fs=
  file: # cannot extract $ARCHIVE_NAME variable
    - $TRAVIS_BUILD_DIR/rm-cstyle-cmts-$TRAVIS_TAG.zip
    - $TRAVIS_BUILD_DIR/rm-cstyle-cmts-$TRAVIS_TAG.tar.gz
    - $TRAVIS_BUILD_DIR/rm-cstyle-cmts-$TRAVIS_TAG-webpack.zip
    - $TRAVIS_BUILD_DIR/rm-cstyle-cmts-$TRAVIS_TAG-webpack.tar.gz
  on:
    repo: jeffy-g/rm-cstyle-cmts
    all_branches: true
    tags: true
