language: node_js

node_js:
  - "12"
  # - "8"
  # - "7"
  # - "6"

# env:
# - TRAVIS_CI=1

cache:
  directories:
  - node_modules

# before_install:
  # - openssl aes-256-cbc -K $encrypted_3058eddffb79_key -iv $encrypted_3058eddffb79_iv -in travis.ppk.enc -out travis.ppk -d
  # - npm install -g codecov

install:
  - yarn install

before_script:
  - yarn dist

script:
  - yarn bench
  - yarn test

after_success:
  # - bash <(curl -s https://codecov.io/bash)
  - codecov -f coverage/coverage-final.json

before_deploy:
  - bash scripts/ci-script.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
   secure: q2e9Ng9HL/jJGGKrIFnMkp2YmjPERIpFxJ8bK3aV1GuFc97ZjBey/WHIRZ/ru3AhpEu6Hpcf/0bviLZpwHwc3urx0PpvYZugnwYngsXhWhaALh8Z/gHOyfTA+1lg/WbaR8bDIPG6nSbI2HSPTEvwiJ7Qlkb0GDC7Hibtib0pgE2Vp0AgcRcVQgkpllTZZz6XNnCaeCagafVKicBCMJ9nVlRgUjzZREh33S5HYTi4OD11GEbzIJoDPRfd3MFLEGhuTwqu4AeCuSQohVluj/I+dCY8s2SzhPQZrojDTmGTUGM0Vq15UVLsNIoBfQWgn25T7HkC45WTnm4jQWCSdPLU4o6RAXLv9TQgSaBaBdu46G1tYVkHdqybMWlXn/jNEFGdrznHvh5lniZ4Q6J5VkUF4HJ/CShL8azGcdIv+5wirkbtrDRtPXBtb1og/xN9SVSd1rdgXVRXgKSUAsGRtNuHWpz//yVMvN8YCzA6hBdLKN927aCy1ZlXrJUMgcLLJRGBQoliWV/flSebrLu2T7/cP+oBJS2zAVohh7URUYTwVRuWQWjJihQvJzT0Yh2uea9A/gQZ/Z1eUISsrAkDPR013GlQ2oMEGTN+ajX+ZeTqIdUKULUiZRA+6JwmVk9I3VTPIfz/uYuKrq4B+Beqjft7r4Tkq4CVQZpQhS/91LX82fs=
  file: # cannot extract $ARCHIVE_NAME variable
    - $TRAVIS_BUILD_DIR/rm-cstyle-cmts-$TRAVIS_TAG.zip
    - $TRAVIS_BUILD_DIR/rm-cstyle-cmts-$TRAVIS_TAG.tar.gz
    - $TRAVIS_BUILD_DIR/rm-cstyle-cmts-$TRAVIS_TAG-webpack.zip
    - $TRAVIS_BUILD_DIR/rm-cstyle-cmts-$TRAVIS_TAG-webpack.tar.gz
  on:
    repo: jeffy-g/rm-cstyle-cmts
    all_branches: true
    tags: true
