# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.5.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - gulp dist
          - npm run bench
          - npm test

          - cd ./dist
          #- zip -r ../rm-cstyle-cmts-release.zip *
          - tar czf ../rm-cstyle-cmts-release.tar.gz *
          - cd ..

          # $BB_REST_API_DOWNLOADs: see Account level Environment variables
          - curl -X POST $BB_REST_API_DOWNLOADs --form files=@"rm-cstyle-cmts-release.tar.gz"
